name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["Bug"]
assignees:
  - DeMineArchiver
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking your time to open an issue!

        Make sure that you've read our [**Contributing Guidelines**](https://github.com/animate-addons/installer/blob/main/CONTRIBUTING.md)
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is
      placeholder: ... doesn't work / Strange behaviour occurs / etc.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: A detailed description of reproducing the bug
      placeholder: |
        1. Launch the app.
        2. Go to ...
        3. Click ...
        4. Profit!
  - type: input
    attributes:
      label: Your Windows version
      description: Please provide your Windows version, along with the build number.
      placeholder: e.g. Windows 11 22H2 build 22621.2070
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Affected Part
      description: Which part of the installer you suppose are affected?
      multiple: true
      options:
        - "App (backend)"
        - "GUI (frontend)"
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [**Code of Conduct**](https://github.com/animate-addons/installer/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
