[package]
name = "animate-addons-installer"
version = "0.0.0"
description = "One application to find, download, install and manage Addons for Adobe Animate"
readme = "../../README.md"
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[build-dependencies]
tauri-build = { workspace = true, features = [] }

[dependencies]
tauri = { workspace = true, features = ["api-all"] }
tauri-plugin-single-instance = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
tauri-plugin-registry = { path = "../tauri-plugin-registry" }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

[features]
custom-protocol = ["tauri/custom-protocol"]
