[package]
name = "tauri-plugin-registry"
version = "0.0.0"
description = ""
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
tauri.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
cfg-if.workspace = true

[target.'cfg(windows)'.dependencies]
winreg.workspace = true
