name: Build the App

on:
  push:
    branches:
      - main
    paths:
      - packages/app/**
  workflow_dispatch:

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      # Clone
      - name: Checkout
        uses: actions/checkout@v3

      # Set up Rust
      - name: Set up Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Load Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./packages/app -> target

      # Set up Node
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn   
      - name: Install dependencies
        run: yarn install

      # Build
      - name: Build
        run: yarn run app:build
      
      # Upload artifacts
      - name: Upload Windows artifact
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: Animate-Addons-Installer-Windows
          path:
            ./packages/app/target/release/Animate-Addons-Installer.exe
